# Data
data_dir: "data/medium_data"
batch_size: 64

# Model
hidden_dim: 512
masking_ratio: 0.75
encoder_num_layers: 6
decoder_num_layers: 4

# Training
learning_rate: 0.00015
max_epochs: 400
accelerator: "gpu"
devices: -1
strategy: "ddp"